version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
  app:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    command: node build/index.js
    ports:
      - "3000:3000"
